name: System info

on:
  workflow_dispatch:

jobs:
  system_info:
    runs-on: ubuntu-latest

    steps:
      - name: Gather System Information
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Labels: ${{ runner.labels }}"
          echo "Processor Architecture: ${{ runner.architecture }}"
          echo "Operating System: ${{ env.RUNNER_OS }}"

