name: System info

on:
  workflow_dispatch:

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy contex

