name: Manual trigger

on:
  workflow_dispatch:

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Get system info
      uses: actions/setup-node@v2
      with:
        script: |
          echo "Operating System Details:"
          uname -a

