name: System info

on:
  workflow_dispatch:

jobs:
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Get runner information
        uses: actions/runner@v2
    
      - name: Print runner details
        run: |
          echo "Runner OS: ${{ steps.runner.outputs.os }}"
          echo "Runner version: ${{ steps.runner.outputs.version }}"

