name: System info

on:
  workflow_dispatch:

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
        
      - name: Operating System Details
        shell: python
        run: |
          import platform
          os_name = platform.system()
          os_release = platform.release()
          os_version = platform.version()
          
          print("Operating System Information:")
          print(f"Operating System: {os_name}")
          print(f"OS Release: {os_release}")
          print(f"OS Version: {os_version}")
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install --upgrade pip psutil

            
  

