name: System info

on:
  workflow_dispatch:

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Hardware context
        shell: python
        run: |
          import platform
          uname = platform.uname()
          print(f"System: {uname.system}")
          print(f"Node Name: {uname.node}")
          print(f"Release: {uname.release}")
          print(f"Version: {uname.version}")
          print(f"Machine: {uname.machine}")
          print(f"Processor: {uname.processor}")
