name: System info

on:
  workflow_dispatch:

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
        
      - name: Operating System Details
        shell: python
        run: |
          import platform
          os_name = platform.system()
          os_release = platform.release()
          os_version = platform.version()
          
          print("Operating System Information:")
          print(f"Operating System: {os_name}")
          print(f"OS Release: {os_release}")
          print(f"OS Version: {os_version}")
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install --upgrade pip install -U py-cpuinfo
      - name: Install dependencies
        run: python -m pip install --upgrade pip install psutil
        
      - name: Hardware  specifications
        shell: python
        run: |
          print("CPU info:")
          import cpuinfo

          info_dict = cpuinfo.get_cpu_info()
          for key, value in info_dict.items():
              print(key, ":", value) 

          print("RAM info:")
          import psutil
          ram_info = psutil.virtual_memory()
          print(f"Total: {ram_info.total / 1024 / 1024 / 1024:.2f} GB")
          print(f"Available: {ram_info.available / 1024 / 1024 / 1024:.2f} GB")
          print(f"Used: {ram_info.used / 1024 / 1024 / 1024:.2f} GB")

          print("Hard disk info:")
          disk_info = psutil.disk_usage("/")
          print(f"Total: {disk_info.total / 1024 / 1024 / 1024:.2f} GB")
          print(f"Used: {disk_info.used / 1024 / 1024 / 1024:.2f} GB")
          print(f"Free: {disk_info.free / 1024 / 1024 / 1024:.2f} GB")
          

            
  

